export const Permissions = Object.freeze({
  CREATE_WORKSPACE: "CREATE_WORKSPACE",
  DELETE_WORKSPACE: "DELETE_WORKSPACE",
  EDIT_WORKSPACE: "EDIT_WORKSPACE",
  CHANGE_WORKSPACE_SETTINGS: "CHANGE_WORKSPACE_SETTINGS",

  ADD_MEMBER: "ADD_MEMBER",
  CHANGE_MEMBER_ROLE: "CHANGE_MEMBER_ROLE",
  REMOVE_MEMBER: "REMOVE_MEMBER",

  CREATE_PROJECT: "CREATE_PROJECT",
  EDIT_PROJECT: "EDIT_PROJECT",
  DELETE_PROJECT: "DELETE_PROJECT",

  CREATE_TASK: "CREATE_TASK",
  EDIT_TASK: "EDIT_TASK",
  DELETE_TASK: "DELETE_TASK",
  CHANGE_TASK_STATUS: "CHANGE_TASK_STATUS",
  SET_TASK_PRIORITY: "SET_TASK_PRIORITY",
  EDIT_TASK_PRIORITY: "EDIT_TASK_PRIORITY",
  ASSIGN_TASK: "ASSIGN_TASK",
  COMMENT_ON_TASK: "COMMENT_ON_TASK",

  VIEW_ONLY: "VIEW_ONLY",
});
